"""add email to order model

Revision ID: 5a48c1ca0fde
Revises: de2c17ff9b08
Create Date: 2026-06-01 07:34:36.827166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a48c1ca0fde'
down_revision: Union[str, Sequence[str], None] = 'de2c17ff9b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE orders SET email = 'manoj@gmail.com' WHERE email IS NULL")
    
    # 3. Change the column to non-nullable
    op.alter_column('orders', 'email', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
