"""add email to order model

Revision ID: acf5dc6bf2f2
Revises: 5a48c1ca0fde
Create Date: 2026-06-01 16:28:00.140172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf5dc6bf2f2'
down_revision: Union[str, Sequence[str], None] = '5a48c1ca0fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
