"""add is_paid to payments

Revision ID: de2c17ff9b08
Revises: 431ba7e2cae4
Create Date: 2026-05-23 17:25:26.587916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2c17ff9b08'
down_revision: Union[str, Sequence[str], None] = '431ba7e2cae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('payments', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_payments_pg_payment_id'), table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payments_pg_payment_id'), 'payments', ['pg_payment_id'], unique=False)
    op.drop_column('payments', 'is_paid')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    # ### end Alembic commands ###
