"""add expires_at to refresh token

Revision ID: ff35b58ff0dd
Revises: cb3211657090
Create Date: 2026-05-12 23:33:42.333615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff35b58ff0dd'
down_revision: Union[str, Sequence[str], None] = 'cb3211657090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'expires_at')
    # ### end Alembic commands ###
